# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.9"
gem "tty-table"
gem "tty-prompt"
gem 'colorize', '~> 0.8.1'
gem 'artii', '~> 2.1', '>= 2.1.2'
gem 'ruby2d', '~> 0.9.2'